### ISSUE TITLE
Does this project work with AppDelegates?

### ISSUE THREAD

**Issue by fatuhoku** [aleph7/MultiDelegate#5]
I think since they're a bit of a special case, if MultiDelegate is shown to work with AppDelegates then it's worth documenting that.

**Comment by alejandro-isaza** [comment]
Not entirely sure what you mean with that. I believe you can only have one app delegate.

**Comment by hokster7** [comment]
@aleph7 well I thought the whole point of `MultiDelegate` is to allow multiple delegates even though normally you're forced only to supply one.

`AppDelegate` is no different, surely?

**Comment by alejandro-isaza** [comment]
The thing is when you call `UIApplicationMain` it only has an option to pass a class name. You don't get a chance to configure your own instance. Therefore you can't use MultiDelegate. What you could do is change the delegate on `application:didFinishLaunchingWithOptions:` to a MultiDelegate but I'm not entirely sure that would work, worth giving it a try.

**Comment by hokster7** [comment]
Don't worry then — I'm not working on iOS any more so not a use case any more. :)
